### ISSUE TITLE
sending request complete to unknown stream result with null pointer

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-gateway#42]
Connect to gw and just send some random complete:

```json
{
  "sid": 10,
  "sig": 2
}
```

Actual Result:
```json
{
  "q": "/io.scalecube.services.error/500",
  "sid": 10,
  "sig": 2,
  "d": {
    "errorCode": 500,
    "errorMessage": "java.lang.NullPointerException"
  }
}
```

Expected Result:
informative error giving indication there is no such stream for the current session.

**Comment by artem-v** [comment]
Fixed at https://github.com/scalecube/scalecube-gateway/pull/44
