### ISSUE TITLE
Release fails due to a snapshot version

### ISSUE THREAD

**Issue by aharonha** [scalecube/scalecube-gateway#79]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5:prepare (default-cli) on project scalecube-gateway-parent: Can't release project due to non released dependencies :
> [ERROR]     io.scalecube:scalecube-gateway-core:jar:2.0.11-SNAPSHOT:compile
> [ERROR] in project 'scalecube-gateway-websocket' (io.scalecube:scalecube-gateway-websocket:jar:2.0.11-SNAPSHOT)
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by aharonha** [comment]
after fixing do `mvn release:prepeare -DdryRun=true`

http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#dryRun

**Comment by artem-v** [comment]
Fixed at https://github.com/scalecube/scalecube-gateway/pull/80
